name = "readest-web"
main = ".open-next/worker.js"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

[[routes]]
pattern = "reader.pdf2epub.ai"
zone_name = "pdf2epub.ai"
custom_domain = true

[vars]
PNPM_VERSION = "10.28.1"

[observability]
enabled = true
head_sampling_rate = 0.01
logs = { head_sampling_rate = 0.01 }
traces = { head_sampling_rate = 0.01 }

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "TRANSLATIONS_KV"
id = "33b2cfdee2ae408fbfe235b0e1e4f20c"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "readest-next-inc-cache"
